name: Slow full Openwrt Build for ARM Cortex-A7

on:
  push:
    branches:
      - openwrt
  workflow_dispatch:

jobs:
  build:
    name: Build ipkg for ARM Cortex-A7
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: openwrt

    steps:
      - name: Checkout openwrt
        uses: actions/checkout@v4
        with:
          path: openwrt
          repository: openwrt/openwrt

      - name: Set openwrt ref
        run: |
          echo "OPENWRT_REF=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          git rev-parse --short HEAD

      - name: Checkout
        uses: actions/checkout@v4  # 升级checkout到v4
        with:
          path: src
          fetch-depth: 0

      - name: Fix Checkout
        run: git fetch --force --tags
        working-directory: src

      - name: Set ref
        run: |
          echo "N3N_REF=$(./scripts/version.sh)" >> $GITHUB_ENV
          ./scripts/version.sh
        working-directory: src

      - name: Copy src package definition
        run: cp -r src/packages/openwrt openwrt/package/n3n

      - name: Cache openwrt source downloads
        uses: actions/cache@v3
        with:
          path: openwrt/dl
          key: openwrt-dl-${{ env.OPENWRT_REF }}-armv7  # 添加架构标识

      - name: Setup ARM Cortex-A7 config
        run: |
          cat << EOF > .config
          CONFIG_TARGET_armvirt=y
          CONFIG_TARGET_armvirt_64=y
          CONFIG_TARGET_ARCH_PACKAGES="arm_cortex-a7_neon-vfpv4"
          CONFIG_TARGET_OPTIMIZATION="-Os -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard"
          EOF

      - name: Add package config
        run: |
          echo "CONFIG_PACKAGE_n3n-edge=m" >> .config
          echo "CONFIG_PACKAGE_n3n-supernode=m" >> .config

      - name: Generate full config
        run: make defconfig

      - name: Download sources
        run: make download

      - name: Build toolchain
        run: make -j $(nproc) tools/install toolchain/install

      - name: Build libpcap
        run: make -j $(nproc) package/libs/libpcap/compile

      - name: Compile n3n packages
        env:
          PKG_VERSION: ${{ env.N3N_REF }}
        run: |
          make package/n3n/{clean,prepare,compile} V=s \
            USE_SOURCE_DIR=$GITHUB_WORKSPACE/n3n

      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # 升级到v4版本
        with:
          name: armv7-packages
          path: openwrt/bin/targets/armvirt/*/packages/*.ipk  # 修正ARM目标路径
